---
title: "Schedule"
output:
  html_document:
    collapsed: false
    number_sections: false
    toc_depth: 1
    theme: united
    highlight: tango
    font-family: Arial
    includes:
      before_body: header.html
      after_body: footer.html
      in_header: GA_script.html
  pdf_document:
    toc_depth: '1'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
library(formattable)
library(lubridate)
```

This syllabus represents my current plans and objectives. As we go through the semester, those plans may need to change to enhance the class learning opportunity. Such changes will be communicated clearly both on the website and in class.


# Scheme of work

Last compiled: `r Sys.Date()`

```{r, echo=FALSE}
fixedWidth = 150

df <- data.frame(
  Week = 1:16,
  Date = seq(as.Date("2025/10/6"), as.Date("2026/1/23"), "weeks"),
  Topics = c("1.1	Introduction to Basic Features of R Programming, 1.2	Logical vectors and relational operators", "1.3	Extracting elements from vector, 1.4	Data Frames and List ", "2.1     Flow control, Introduction to Function", 
             "Introduction to Function, Packages, libraries, and Repositories", "Importing data into R", 
             "Programming Statistical Graphics- Base", "**MID SEMESTER BREAK**", "Programming Statistical Graphics - ggplot2", 
             "Data Cleaning and Filtering", "Data Cleaning and Filtering", 
             "Basic Statistical Analysis", "Basic Statistical Analysis", 
             "**SPECIAL BREAK**", "Basic Statistical Analysis", "Basic Statistical Analysis", 
             "Basic Statistical Analysis"),
  Hours = c("4", "4", "3", "3", "3", "3", "", "3", "3", "3", "3", "3", "", "3", "3", "3"),
  Reading = c("[Notes](https://ciksuriyati.github.io/learnR/page-a.html)", 
              "[Notes](https://ciksuriyati.github.io/learnR/page-b.html)", 
              "[Notes](https://ciksuriyati.github.io/learnR/page-c.html)", 
              "[Notes](https://ciksuriyati.github.io/learnR/page-d.html)", 
              "[Notes](https://ciksuriyati.github.io/learnR/page-e.html)", 
              "[Notes](https://ciksuriyati.github.io/learnR/page-f.html)", "",
              "[Notes](https://ciksuriyati.github.io/learnR/page-g.html)", 
              "[Notes](https://ciksuriyati.github.io/learnR/page-h.html)", 
              "[Notes](https://ciksuriyati.github.io/learnR/page-i.html)", 
              "[Notes](https://ciksuriyati.github.io/learnR/page-j.html)", 
              "[Notes](https://ciksuriyati.github.io/learnR/page-k.html)", "",
              "[Notes](https://ciksuriyati.github.io/learnR/page-l.html)", 
              "[Notes](https://ciksuriyati.github.io/learnR/page-m.html)",
              "[Notes](https://ciksuriyati.github.io/learnR/page-n.html)"),
  CheatSheet = c("[Base R](https://iqss.github.io/dss-workshops/R/Rintro/base-r-cheat-sheet.pdf)", 
                 "[Base R](https://iqss.github.io/dss-workshops/R/Rintro/base-r-cheat-sheet.pdf)", 
                 "[Base R](https://iqss.github.io/dss-workshops/R/Rintro/base-r-cheat-sheet.pdf)", 
                 "[Base R](https://iqss.github.io/dss-workshops/R/Rintro/base-r-cheat-sheet.pdf)", 
                 "[readr](https://rstudio.github.io/cheatsheets/data-import.pdf)", 
                 "[Base::Graph](http://publish.illinois.edu/johnrgallagher/files/2015/10/BaseGraphicsCheatsheet.pdf)", "",
                 "[ggplot2](https://rstudio.github.io/cheatsheets/data-visualization.pdf)", 
                 "[ggplot2](https://rstudio.github.io/cheatsheets/data-visualization.pdf)", 
                 "[tidyr](https://rstudio.github.io/cheatsheets/tidyr.pdf)", 
                 "[dplyr](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)", 
                 "[stats](https://4va.github.io/biodatasci/handouts/r-stats-cheatsheet.pdf)", "",
                 "", 
                 "[stats](https://4va.github.io/biodatasci/handouts/r-stats-cheatsheet.pdf)",
                 "[stats](https://4va.github.io/biodatasci/handouts/r-stats-cheatsheet.pdf)"),
  Remarks = c("Installation of RStudio Desktop, Signup for Posit Cloud, Google Colab, and Kaggle",
              "Focus more on `for{}` loop and `If-else` statement",
              "1. Create a function to automate data preprocessing (e.g., Missing value detection, etc.)",
              "2. R-project website, Bioconductor, and GitHub",
              "Focus on Histogram, Scatter diagram, Bar chart, Box plot, and Line chart",
              "Advanced visualization techniques and interactive plots",
              "",
              "Data cleaning and preprocessing techniques",
              "Data transformation and manipulation",
              "Statistical analysis fundamentals",
              "Hypothesis testing and confidence intervals",
              "Regression analysis and correlation",
              "",
              "Advanced statistical modeling",
              "Project preparation and presentation skills",
              "Final project presentation and report submission"),
  Assessment = c("","","","","","","","Quiz","","",  "", "", "","", "Test","Presentation & Report"),
  Mark = c("","","","","","","","15%","","",  "", "", "","", "30%","25% & 30%"))

formattable(df, 
            align =c("l","l","l","c","c", "c", "c", "c", "c", "r"), 
            list(
Date = formatter("span", style = ~ style(color = "Blue"),  `border-radius` = "4px", `padding-right` = "2px") ,
Topics = color_bar("#e9c46a"),
Assessment = color_bar("#48cae4"),
CheatSheet = color_bar("lightgray"),
Remarks = color_bar("#a8e6cf"),
Mark = color_bar("#f28482"))
            )

```

