---
title: "Week 14"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: united
    highlight: tango
    df_print: paged
    toc: true
    toc_depth: 2

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



In this topic, you will learn about :

- Presentation guidelines
- Written report Rubrics

# {.tabset}

## Presentation

### Presentation (25% of ongoing assessment)

The main aim of this presentation is to promote self-efficacy in handling data in a meaningful manner.

**Instruction:**

- Conduct a simple data analysis with proper steps in analysing the data using R programming. 
- You may choose any dataset that is freely available and conduct a proper data analysis procedure. 
- Demonstrate and promote your ability to analyse data from scratch in a meaningful manner. 
- The objective of the data analysis and presentation is to promote self-skill in analysing data and knowledge transfer to the community. 
- **AT LEAST ONE DESCRIPTIVE STATISTICS and ONE INFERENTIAL STATISTICS** should be included in the analysis. 
- The presentation should be delivered in public with the following requirements:

1) Introduction
2) Objective(s)
3) Methodology
4) Analysis (Demonstrate the steps of analysis using RStudio).
5) Results
6) Conclusion
7) Benefit of the analysis

There is no restricted format in presentation delivery.

**NOTE:** It is advisable to create a social media group with many stakeholders from industries, academics, and local community.





## Written Report

### Written Report (30% of ongoing assessment)

Topic 1 to 6

|                                    | **Assessment criteria**                                                                                                                                                                                                      | **Weight (W)** | **Score (1 -10)** | **Marks (W*S)** |
|------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:--------------:|:-----------------:|-----------------|
| **Introduction**                   | Appropriate title; clear problem statement; well-defined project scope; clear, measurable and achievable objectives; and significant to the community and  practitioners.                                                    |        3       |                   |                 |
| **Literature Review**              | Review of current, related literature and research reports. Consist of relevant, correct facts and substantial references - able to identify, collect, summarize and analyze relevant and latest/issues of subject matter.)  |        2       |                   |                 |
| **Methodology**                    | A detailed and in depth explanation of the appropriate approach, methods, sources and deliverables in accomplishing the project.                                                                                             |        4       |                   |                 |
| **Results / Findings**             | The result of research carried out to solve the problem defined. This may include analysis, usability, design, implementation, testing, prototype or framework.                                                              |        5       |                   |                 |
| **Conclusion and Recommendations** | Conclusion of what has been achieved, explaining limitations/problems and recommendation for future work.                                                                                                                    |        2       |                   |                 |
| **Report Presentation**            | Structure, organisation and standard report format. Clarity of language, consistency of the content, logical flow and use of figurative language for all materials.                                                          |        2       |                   |                 |
| **References and Citations**       | Standard citation and references based on the guideline given. Valid source of references and other appropriate supporting documents.                                                                                        |        2       |                   |                 |


### PROJECT EVALUATION RUBRIC (REPORT)

| No | **Assessment criteria**            | Excellence (8-10)                                                                                                                                                                                                                                                                                                                                             |                                                                                                                                                        Good (6-7)                                                                                                                                                       |                                                                                                                                                         Satisfactory (5)                                                                                                                                                         | Poor (1-4)                                                                                                                                                                                                                                                                                                                                       |
|----|------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1  | **Introduction**                   | - Working title that clearly reflects the project. - Well defined problem statement. Provides exceptionally clear context supporting rationale for project; clear statement of why project is needed. - Objectives - highly reflect the following elements: a. Specific b. Measurable c. Achievable d. Realistic e. Timeliness f. Well-defined project scope. | Working title that reflects the project.  Clear problem statement. Provides clear context supporting rationale for project; clear statement of why project is needed.  Objectives - clearly reflect the following elements: a. Specific b. Measurable c. Achievable d. Realistic e. Timeliness  Clear project scope. | Appropriate working title that reflects the project.  Adequate problem statement. Provides context supporting rationale for project; statement of why project is needed.  Objectives - adequately reflect the following elements: a. Specific b. Measurable c. Achievable d. Realistic e. Timeliness  Adequate project scope. | Inappropriate working title that reflects the project.  Unclear problem statement, poor statement of context supporting rationale for project, statement of why project is needed.  Objectives - does not reflect the following elements: a. Specific b. Measurable c. Achievable d. Realistic e. Timeliness  Not well-defined project scope. |
| 2  | **Literature Review**              | Thorough review of relevant and empirical sources, citing seminal works in the field. Exemplary synthesis and organization of literature that is clearly linked to project question. Specific attention to diversity issues pertaining to project topic.                                                                                                      | Good review of relevant and empirical sources, citing seminal works in the field. Good synthesis and organization of literature that is clearly linked to project question. Attention to diversity issues pertaining to project topic.                                                                                  | Adequate review of relevant and empirical sources. Adequate synthesis and organization of literature that is linked to project question. Some attention to diversity issues pertaining to project topic.                                                                                                                         | Incomplete or poorly developed review ofliterature; problems withorganization; weak linkage toproject topic.                                                                                                                                                                                                                                     |
| 3  | **Methodology**                    | Highly reflects the following elements: 1. Reference population and samples 2. Design 3. Sampling techniques 4. Instrument tools 5. Methods 6. Operational Definition 7. Flow Chart                                                                                                                                                                           | Clearly reflects the following elements:  Reference population and samples  Design  Sampling techniques  Instrument tools  Methods  Operational Definition  Flow Chart                                                                                                                                           | Adequately reflects the following elements:  Reference population and samples  Design  Sampling techniques  Instrument tools  Methods  Operational Definition  Flow Chart                                                                                                                                                 | Poorly reflects the following elements:  Reference population and samples  Design  Sampling techniques  Instrument tool  Methods  Operational Definition  Flow Chart                                                                                                                                                                      |
| 4  | **Results/Findings**               | Professional looking and accurate representation of the result in tables and/or graphs. Graphs and tables are labeled and titled. Critical analysis of the results.                                                                                                                                                                                           | Accurate representation of the result in tables and/or graphs. Graphs and tables are labeled and titled. Contain some result analysis.                                                                                                                                                                                  | Accurate representations of the result in written form, but no graphs or tables are presented.                                                                                                                                                                                                                                   | Results are not shown or are inaccurate.                                                                                                                                                                                                                                                                                                         |
| 5  | **Conclusion and Recommendations** | Conclusion includes the findings, lesson learned from the project. Future recommendations to real life situations are highly stated.                                                                                                                                                                                                                          | Conclusion includes the findings and lesson learned from the project. Recommendations for future work are stated.                                                                                                                                                                                                       | Conclusion includes the findings or lesson learned from the project. Some recommendations for future work are stated.                                                                                                                                                                                                            | No conclusion or recommendations were included in the report.                                                                                                                                                                                                                                                                                    |
| 6  | **Report Presentation**            | The report is well structured and organized following the standard research reporting procedure/format. Sentences are complete and grammatical, and theyflow together easily. All figures, graphs, charts and drawings are accurate, consistent with the text and of good quality.                                                                            | The report is structured and organized following the standard research reporting procedure/format. Sentences are complete with minor grammatical errors. Figures, graphs, charts and drawings are not accurate but consistent with the text.                                                                            | The report is poorly structured and organized but following the standard research reporting procedure/format. Sentences are complete with major grammatical errors. Figures, graphs, charts and drawings are not accurate and not consistent with the text.                                                                      | The report does not follow the standard research reporting procedure/format. Poor grammar structure. All figures, graphs, charts and drawings are of bad quality.                                                                                                                                                                                |
| 7  | **References and Citations**       | Contain relevant references and citations.                                                                                                                                                                                                                                                                                                                    | Contain some relevant references and citations.                                                                                                                                                                                                                                                                         | Contain a few relevant references and citations.                                                                                                                                                                                                                                                                                 | Contain irrelevant references and very few citations.                                                                                                                                                                                                                                                                                            |