---
title: "Syllabus"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: united
    highlight: tango
    df_print: paged
    toc: true
    toc_depth: 2
---


## Introduction to Statistical Programming

Course code: STA334\
Credit hour: 4\
Semester: October 2023 - February 2024

**Instructor**

Suriyati Ujang\
Email: suriyatiujang@uitm.edu.my

**Class location**

Times:


**Office Hours**

by appointment.

**Website**

The syllabus and other relevant class information and resources will be posted here. Changes to the schedule will be posted to this site so please try to check it periodically for updates.

**Prerequisite Knowledge and Skills**

Knowledge of basic programming to provide context for exercises.

**Teaching Philosophy**

This class is taught using a flipped, learner-centered, approach, because learning to program and work with data requires actively working on computers.

## Course Policies

**Attendance Policy**

Attendance will not be taken or factor into the grades for this class. However, experience suggests that students who regularly miss class struggle to learn the material.

**Quiz/Exam Policy**

All quizzes are will be informed as semester ongoing. The estimated week for:

1. Quiz - Week 6 or 7
2. Test - Week 13 or 14

**Course Technology**

Students are required to provide their own laptops and to install free and open source software on those laptops (see Setup for installation instructions). If you don’t have access to a laptop please contact the instructor.

**UiTM Policies**

Students should visit https://aims.uitm.edu.my/index.cfm/page/module/moduleId/159206 and review all syllabus statement information. 

**Disclaimer:**\
This syllabus represents my current plans and objectives. As we go through the semester, those plans may need to change to enhance the class learning opportunity. Such changes will be communicated clearly both on the website and in class.

## Scheme of Work

| **Week** | **Topic**                                                                                                                                                                           | **Remarks**                                                                               |
|:--------:|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------|
| 1        | Topic 1: Introduction to R language - Introduction to basic features of R programming - Logical vectors and relational operators                                                    |    Entrance Survey                                                                        |
| 2        |  Topic 1: (cont’d)  - Extracting elements from vectors  - Data frames and list                                                                                                      |                                                                                           |
| 3        |    Topic 2: Programming with R    - Flow control    - Introduction to function                                                                                                      |                                                                                           |
| 4        |    Topic 2: (cont’d)    - Introduction to function    - Packages, libraries, and repositories                                                                                       |                                                                                           |
| 5        | Topic 3: Importing data into R  - Importing from flat files with “utils” base package - Importing Excel data file - Importing data from other statistical software - Exporting data |    Focus on Histogram, Scatter diagram, Bar chart, Box plot, and Line chart               |
| 6        |    Topic 4: Programming statistical graphics    - Plotting using base package (graphics)                                                                                            | Focus on Histogram, Scatter diagram, Bar chart, Box plot, and Line chart  **Online Quiz** |
| 7        |    Topic 4: (Cont’d)    - Plotting using ggplot2                                                                                                                                    |                                                                                           |
| 8        | Topic 5: Data Cleaning and filtering  - Introduction to tidy data - Introduction to tidyr package                                                                                   |    Discuss project                                                                        |
| 9        |    Topic 5: (Cont’d)    - Missing Data    - Keep and remove variables    - Filtering data and variables                                                                             |    Discuss project                                                                        |
| 10       | Topic 6: Basic Statistical Analysis  - Summary statistics, frequency, and cross tabulation data                                                                                     |    Discuss project                                                                        |
| 11       |    Topic 6: (Cont’d)    - Test of mean (test of single mean, independent t-test, paired t-test, and one-way ANOVA)                                                                  |                                                                                           |
| 12       |    Topic 6: (Cont’d)  - Test of association (Pearson Chi-Square and Fisher’s Exact test)                                                                                            | **Presentation**                                                                          |
| 13       |   Topic 6: (Cont’d)    - Correlation test                                                                                                                                           | **Test**                                                                                  |
| 14       |   Topic 6: (Cont’d)    - Linear regression (simple and multiple linear regression)                                                                                                  | **Report submission**                                                                     |


### References

https://aims.uitm.edu.my/index.cfm/page/module/moduleId/159206

Back to main website [_Miss Sue_](https://sites.google.com/view/suriyatiujang/home?authuser=0)